api:
  llm:
    base_url: "${LLM_BASE_URL}"
    model: "${LLM_MODEL}"
  github:
    owner: "${GITHUB_ORG}"
  slack:
    channel: "${SLACK_CHANNEL}"

processing:
  limits:
    max_input_tokens_per_request: ${MAX_INPUT_TOKENS_PER_REQUEST}
  batch:
    cleanup: ${BATCH_CLEANUP}
    keep_days: ${KEEP_DAYS}
    generated_files_directory: "batch_files"
  history:
    default_lookback_hours: ${DEFAULT_LOOKBACK_HOURS}
    use_last_run_file: ${USE_LAST_RUN_FILE}

runtime:
  debug: ${DEBUG} 